
name = "DashDraggable"
uuid = "1b08a953-4be3-4667-9a23-b388bd78db4c"
authors = ["Mehdi Echchelh <mehdi.echel@gmail.com>"]
version = "0.1.1a"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
